name: MSBuild

on:
  pull_request:
    paths-ignore:
      - '**/README.md'

env:
  SOLUTION_FILE_PATH: CP_Main_10.sln
  CI_PLATFORM_TOOLSET: v143

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Restore native NuGet packages
        shell: pwsh
        run: .\.github\scripts\Restore-NativePackages.ps1

      - name: Build 64bit
        run: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=${{ env.CI_PLATFORM_TOOLSET }}
